/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AStep: typeof import('ant-design-vue/es')['Step']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    LoginForm: typeof import('./components/login/LoginForm.vue')['default']
    LoginModal: typeof import('./components/LoginModal.vue')['default']
    PhoneCodeFields: typeof import('./components/login/PhoneCodeFields.vue')['default']
    RegisterStepAccount: typeof import('./components/login/RegisterStepAccount.vue')['default']
    RegisterStepAuth: typeof import('./components/login/RegisterStepAuth.vue')['default']
    RegisterStepIdentity: typeof import('./components/login/RegisterStepIdentity.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteQrBlock: typeof import('./components/SiteQrBlock.vue')['default']
    SubPageLayout: typeof import('./components/SubPageLayout.vue')['default']
  }
}
