/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    ASelect: typeof import('ant-design-vue/es')['Select']
    AStep: typeof import('ant-design-vue/es')['Step']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    BreadcrumbNav: typeof import('./components/BreadcrumbNav.vue')['default']
    DetailCard: typeof import('./components/common/DetailCard.vue')['default']
    DetailPageShell: typeof import('./components/common/DetailPageShell.vue')['default']
    DetailTabs: typeof import('./components/common/DetailTabs.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    FilterRow: typeof import('./components/common/FilterRow.vue')['default']
    LoginForm: typeof import('./components/login/LoginForm.vue')['default']
    LoginModal: typeof import('./components/LoginModal.vue')['default']
    PagedTable: typeof import('./components/common/PagedTable.vue')['default']
    PageState: typeof import('./components/PageState.vue')['default']
    PaginationBar: typeof import('./components/common/PaginationBar.vue')['default']
    PanelTabs: typeof import('./components/common/PanelTabs.vue')['default']
    PhoneCodeFields: typeof import('./components/login/PhoneCodeFields.vue')['default']
    RegisterStepAccount: typeof import('./components/login/RegisterStepAccount.vue')['default']
    RegisterStepAuth: typeof import('./components/login/RegisterStepAuth.vue')['default']
    RegisterStepIdentity: typeof import('./components/login/RegisterStepIdentity.vue')['default']
    ResultCountBar: typeof import('./components/common/ResultCountBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchRow: typeof import('./components/common/SearchRow.vue')['default']
    SectionTitle: typeof import('./components/common/SectionTitle.vue')['default']
    SelectedConditionsBar: typeof import('./components/common/SelectedConditionsBar.vue')['default']
    SiteQrBlock: typeof import('./components/SiteQrBlock.vue')['default']
    SubPageLayout: typeof import('./components/SubPageLayout.vue')['default']
    UserAccountMenu: typeof import('./components/UserAccountMenu.vue')['default']
    VipPromoModal: typeof import('./components/VipPromoModal.vue')['default']
  }
}
